input_device_name: null
output_device_name: null
input_rate: 24000
output_rate: 24000
frame_period: 5
buffer_time: 1
extract_f0_mode: world
vocoder_buffer_size: 1024
input_scale: 0.125
output_scale: 2.0
input_silent_threshold: 80
output_silent_threshold: 80
encode_extra_time: 0.0
convert_extra_time: 0.5
decode_extra_time: 0.0

input_statistics_path: './sample/model_stage1/predictor.npz'
target_statistics_path: './sample/model_stage1/config.json'
stage1_model_path: './sample/model_stage2/predictor.npz'
stage1_config_path: './sample/model_stage2/config.json'
stage2_model_path: './sample/input_statistics.npy'
stage2_config_path: './sample/tareget_statistics.npy'
